project:
  type: website
  output-dir: website
  execute-dir: project

website:
  title: "GEARS"
  repo-url: https://github.com/renatovargas/gears/
  repo-actions: [source]
  repo-branch: master
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Download"
        href: download.qmd
      - text: "Documentation"
        href: documentation/index.qmd
      - about.qmd
      
  sidebar:
    - title: "Documentation"
      style: "docked"
      contents:
        - text: "Documentation"
          href: documentation/index.qmd
        - section: "Guides"
          contents:
            - text: "GEARS User Guide"
              href: documentation/guides/gears-user-guide.qmd
        - section: "Methods"
          contents:
            - text: "Overview"
              href: documentation/methods/overview.qmd
          
format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



