project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "GEARS"
  repo-url: https://github.com/renatovargas/gears/
  repo-actions: [source]
  repo-branch: master
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



