project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "gears"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



