{
  "hash": "1083cced4418733d55c0fdda3489aa45",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PolOpT Emissions Database Construction\"\nsubtitle: \"Datasets and approaches (DRAFT FOR DISCUSSION)\"\nauthor:\n  - name: \"Renato Vargas\"\n    id: rv\n    affiliation: \n      - name: Food and Agriculture Organization (FAO)\n  - name: \"Martin Cicowiez\"\n    id: mc\n    affiliation: \n      - name: Food and Agriculture Organization (FAO)\nabstract: |\n  Through a series of reproducible data processing routines, different sources are combined into a single database that aims to lower the barrier of entry to emissions analysis for Computable General Equilibrium and Input-Output practitioners who work with national macroeconomic datasets that lack this dimension (social accounting matrices or supply and use tables). While this effort is initially intended to provide ESA’s [Policy Optimization Modelling Tool (PolOpT)](https://openknowledge.fao.org/items/a9b06566-1128-4032-9c6e-203211f1d288) with emissions data, other analysts, officers and initiatives from the environmental accounting space can benefit from it. \n\nformat:\n  html:\n    toc: true\n  pdf:\n    toc: true\n    number-sections: false\n    colorlinks: true\neditor_options: \n  chunk_output_type: console\n  render-on-save: true\nbibliography: references.bib\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Introduction\n\nThe Monitoring and Analyzing Food and Agricultural Policies (MAFAP) programme seeks to establish country owned and sustainable systems to monitor, analyze, and reform food and agricultural policies to enable more effective, efficient and inclusive policy frameworks. Since policies are only enacted when they are properly funded, FAO’s Policy Optimization Tool (PolOpT) [@sanchez_cicowiez_2022; @sanchez_cicowiez_2023] is particularly geared towards helping countries---the agricultural public sector, in particular---optimize public budgets in the face of competing objectives, like economic growth, job creation, poverty reduction, or access to affordable healthy diets, for example.\n\nIn the face of increasing vulnerability, climate risk mitigation and adaptation objectives have also become a part of the policy dialogue, as different international commitments (e.g. the Paris Agreement) present new demands and challenges to governments. Leadership of the Gates Foundation, the main donor of the MAFAP programme, has expressed interest in the MAFAP programme being able to bring climate change into the competing priorities of its analysis for policymakers. The Global Emissions Database aims to provide a seamless integration of data on anthropogenic emissions of greenhouse gases and air pollution with structural analysis frameworks like Computable General Equilibrium and Input-Output models used by the MAFAP programme in general, or the PolOpT in particular.\n\nHere we describe the approach used to construct an anthropogenic emissions accounting satellite framework by economic activity and driver, using globally available datasets. We aim to maintain compatibility with the System of National Accounts (SNA) with which economic performance is measured [@europeancommission2009]. Where possible, we adopt approaches suggested by previous efforts at harmonization between Greenhouse Gas Inventories and SEEA pilot implementations [@eurostat2015; @flachenecker2018; @gutman2024].\n\nEmissions from combustion are estimated at the economic activity level using the International Industrial Standard Classification---ISIC---[@united_nations_international_2008] and driver, using the Tier 1 method of the Intergovernmental Panel on Climate Change—IPCC—[@ipcc1996; @ipcc2006] and energy use information from the Energy Statistics Database [@unsd2023]. Emissions from Industrial Processes and Waste come from EDGAR [@crippa2023] and are mapped to economic activities following a broadly tested global approach that facilitates use with CGE frameworks; i.e. that of the Global Trade Analysis Project---GTAP---[@aguiar2019; @chepeliev2024a]. Emissions from Agriculture are sourced from FAOSTAT [@fao2024] and mapped to ISIC economic activities. Individual drivers are left for the practitioner to map to their own structure (i.e. output by industries, endowment by industries, input use by industries, and consumption by households). \n\n# Methodology\n\n## Overview\n\nOur goal is to leverage valuable emissions data from different sources and we have scripted data processing routines to ingest original datasets in tabular format (mainly Excel Files and Comma Separated Values) and manipulate them to conform to a single flat file structure, using the R programming language [@Rcore2024][^1]. The original datasets, translated into the much smaller size RDS binary format, as well as the processing scripts, are included with the resulting emissions database repository[^3]. \n\n[^1]: R was chosen for its information management and data compression facilities. However, the principles used can be easily implemented in Python, Stata, or any other language with similar affordances.\n\n[^3]: The data is available at: [https://renatovargas.github.io/emdb/download.html](https://renatovargas.github.io/emdb/download.html)\n\n## Total Emissions from EDGAR\n\n We start with the sourcing of The Emissions Database for Global Atmospheric Research---EDGAR---(Crippa et al., 2023) datasets published by the European Commission because they are comprehensive, covering most of the greenhouse gas emissions inventories domains as shown in @tbl-edgar-domains, belonging to 1) energy; 2) Industrial processes and product use; 3) Agriculture, forestry, and other land use; 4) Waste; and 5) Other (mainly indirect emissions from deposition of Nitrogen). This allows us to provide an overview of the coverage needed by our dataset. However, due to the form in which the data is presented in the EDGAR data and our database needs, we only take advantage of emissions data on industrial processes, waste, and \"other\" (which refers mainly to emissions from the atmospheric deposition of nitrogen). To avoid double counting, we replace emissions from the use of energy (Chapter 1A) with data from the UN Energy Database [@unsd2023] and emissions from agriculture, forestry, and other land use with data from FAOSTAT [@fao2024]. For comparison purposes, it is important to note that large scale biomass burning with Savannah burning, forest fires, and sources and sinks from land-use, land-use change and forestry (LULUCF) are not covered in EDGAR, but are in FAOSTAT.\n\n| **Code** | **IPCC Greenhouse Gas Inventory domain** |\n| :--| :--------|\n| **1.A.1.a** | Main Activity Electricity and Heat Production |\n| **1.A.1.bc** | Petroleum Refining - Manufacture of Solid Fuels and Other Energy Industries |\n| **1.A.2** | Manufacturing Industries and Construction |\n| **1.A.3.a** | Civil Aviation |\n| **1.A.3.b_noRES** | Road Transportation no resuspension |\n| **1.A.3.c** | Railways |\n| **1.A.3.d** | Water-borne Navigation |\n| **1.A.3.e** | Other Transportation |\n| **1.A.4** | Residential and other sectors |\n| **1.A.5** | Non-Specified |\n| **1.B.1** | Solid Fuels |\n| **1.B.2** | Oil and Natural Gas |\n| **2.A.1** | Cement production |\n| **2.A.2** | Lime production |\n| **2.A.3** | Glass Production |\n| **2.A.4** | Other Process Uses of Carbonates |\n| **2.B** | Chemical Industry |\n| **2.C** | Metal Industry |\n| **2.D** | Non-Energy Products from Fuels and Solvent Use |\n| **2.E** | Electronics Industry |\n| **2.F** | Product Uses as Substitutes for Ozone Depleting Substances |\n| **2.G** | Other Product Manufacture and Use |\n| **3.A.1** | Enteric Fermentation |\n| **3.A.2** | Manure Management |\n| **3.C.1** | Emissions from biomass burning |\n| **3.C.2** | Liming |\n| **3.C.3** | Urea application |\n| **3.C.4** | Direct N2O Emissions from managed soils |\n| **3.C.5** | Indirect N2O Emissions from managed soils |\n| **3.C.6** | Indirect N2O Emissions from manure management |\n| **3.C.7** | Rice cultivations |\n| **4.A** | Solid Waste Disposal |\n| **4.B** | Biological Treatment of Solid Waste |\n| **4.C** | Incineration and Open Burning of Waste |\n| **4.D** | Wastewater Treatment and Discharge |\n| **5.A** | Indirect N2O emissions from the atmospheric deposition of nitrogen in NOx and NH~3~ |\n| **5.B** | Fossil fuel fires |\n\n: EDGAR greenhouse gas inventory domain coverage {#tbl-edgar-domains}\n\nSource: authors based on Crippa, et al. (2023).\n\n EDGAR datasets contain disaggregated information for the elements in the table above in Gigagrams for CO~2~, CO~2~ from biofuels, CH~4~, N~2~O, and Fluorinated greenhouse gases (F-Gases) PFC, HFC, HCFC, and NF~3~. However, while they provide a single dataset with aggregate GHG emissions expressed in CO~2~eq using the Global Warming Potential values of the Fifth Assessment Report of the IPCC with a 100-year horizon, all gases are summed into a single figure for each element in @tbl-edgar-domains, not distinguished from the individual shares of CO~2~ tons equivalent contributed by each gas. For that reason, we used the individualized datasets per gas in Gigagrams and performed the Global Warming Potential AR5 calculation ourselves using coefficients from Myhre et al. @myhre2013, except for F-Gases, for which the conversion was made by EDGAR and kept separate as needed.\n\n| Gas                 | Global Warming Potential Values AR5 100-year horizon |\n| :-- | :-------- |\n| Methane (CH4)       | 28 CO~2~ tons equivalent / Gigagram                  |\n| Nitrous Oxide (N2O) | 265 CO~2~ tons equivalent / Gigagram                 |\n\n: Conversion coefficients for methane and nitrous oxide {#tbl-conversion-ar5}\n\nSource: @myhre2013 [p. 731].\n\nAs explained above, while the Edgar dataset is very comprehensive, it lacks the disaggregation by driver (intermediate input, output, endowment, or consumption) to satisfy the needs of CGE studies, when it comes to energy and certain agricultural aspects. That means that it is possible to identify to which volume of the IPCC a certain emission value belongs, but not which fuel product is responsible for it. For example, we can identify that CO~2~ emissions are emitted by the Road Transportation sector, but not whether the emissions come from the burning of Diesel or from Bioethanol or any other fuel type. For that reason, we replace the values related to energy with those from our own estimates using the United Nations Energy Database and default emission factors, as well as those elements related to agriculture and LULUCF with emissions data from FAOSTAT at the driver level (explained in the FAOSTAT section below). For completeness, the remaining domains; i.e. industrial processes, waste, and others are linked to total output of specific economic activities, using the International Standard Industrial Classification (United Nations, 2008) where possible (see @tbl-edgar-isic-map).\n\n\n| IPCC Code | IPCC | ISIC Code | ISIC |\n| :--: | :---- | :--: | :---- |\n| 2.A.1 | Cement production | 2394 | Manufacture of cement, lime and plaster |\n| 2.A.2 | Lime production | 2394 | Manufacture of cement, lime and plaster |\n| 2.A.3 | Glass Production | 2310 | Manufacture of glass and glass products |\n| 2.A.4 | Other Process Uses of Carbonates | 9999 | Undetermined |\n| 2.B | Chemical Industry | 2011 | Manufacture of basic chemicals |\n| 2.C | Metal Industry | 2410 | Manufacture of basic iron and steel |\n| 2.D | Non-Energy Products from Fuels and Solvent Use | 9999 | Undetermined |\n| 2.E | Electronics Industry | 2640 | Manufacture of consumer electronics |\n| 2.F | Product Uses as Substitutes for Ozone Depleting Substances | 9999 | Undetermined |\n| 2.G | Other Product Manufacture and Use | 9999 | Undetermined |\n| 4.A | Solid Waste Disposal | 3821 | Treatment and disposal of non-hazardous waste |\n| 4.B | Biological Treatment of Solid Waste | 3822 | Treatment and disposal of hazardous waste |\n| 4.C | Incineration and Open Burning of Waste | 3822 | Treatment and disposal of hazardous waste |\n\n: Mapping from EDGAR to individual ISIC economic activities {#tbl-edgar-isic-map}\n\n## Emissions from Agriculture and LULUCF\n\nData on CO~2~, CH~4~, and N~2~O emissions from Agriculture, Forestry, and Other Land Use, including Land Use Change were sourced from FAOSTAT[^2]. The level of disaggregation of its individual datasets allows us to identify the driving agricultural product (crop) or endowment (animal assets or cropland area) behind the emission of a specific gas. Since values are expressed in kilotons (kt) of each GHG, we converted them to Global Warming Potential AR5 for a 100-year horizon using the values in @tbl-conversion-ar5. To facilitate the mapping to CGE and Input-Output frameworks, we added a correspondence to individual ISIC economic activities responsible for the emission, where possible.  \n\n[^2]: Datasets are available at [https://www.fao.org/faostat/en/#data](https://www.fao.org/faostat/en/#data) under the heading \"Climate Change: Agrifood systems emissions\".\n\nFAOSTAT datasets go beyond the elements stipulated in the third category of an IPCC inventory, and provide information on energy use by the agricultural sector, as well as emissions from industrial processes and waste. Since we source those from EDGAR for all economic sectors, we only use data from the domains shown in @tbl-faostat-domains from FAOSTAT.\n\n\n\n::: {#tbl-faostat-domains .cell tbl-cap='FAOSTAT domains sourced'}\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}ll}\n\\toprule\nCode & Sector \\\\ \n\\midrule\\addlinespace[2.5pt]\n3.B.1.a & LULUCF - Forestland \\\\ \n3.B.1.b & LULUCF - Net Forest conversion \\\\ \n3.B.2 & LULUCF - Drained organic soils (CO2) \\\\ \n3.B.6.a & LULUCF - Fires in organic soils \\\\ \n3.B.6.b & LULUCF - Forest fires \\\\ \n3.C.1.c & Agriculture - Savanna fires \\\\ \n3.C.5 & Agriculture - Drained organic soils (N2O) \\\\ \n3.A.1 & Agriculture - Enteric fermentation (Emissions CH4) \\\\ \n3.A.2.a & Agriculture - Emissions (N2O) (Manure applied) \\\\ \n3.A.2.b & Agriculture - Manure management (Emissions N2O) \\\\ \n3.A.2.c & Agriculture - Manure management (Emissions CH4) \\\\ \n3.C.6 & Agriculture - Manure left on pasture (Emissions N2O) \\\\ \n3.C.4 & Agriculture - Synthetic Fertilizers \\\\ \n3.C.1.a & Agriculture - Burning crop residues (Emissions CH4) \\\\ \n3.C.1.b & Agriculture - Burning crop residues (Emissions N2O) \\\\ \n3.C.7 & Agriculture - Rice cultivation (Emissions CH4) \\\\ \n3.C.8 & Agriculture - Crop residues (Emissions N2O) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nMore importantly, the reason why we replaced the data from EDGAR on agriculture emissions with FAOSTAT is because of the ability to differentiate the different drivers of those emissions, as well as the separate totals by gas. @tbl-faostat-subsectors shows the different elements from FAOSTAT available for practitioners to map to inputs, outputs, endowments, or consumption. \n\n\n::: {#tbl-faostat-subsectors .cell tbl-cap='FAOSTAT domains sourced'}\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rl}\n\\toprule\nCode & Driver \\\\ \n\\midrule\\addlinespace[2.5pt]\n0015 & Wheat \\\\ \n0027 & Rice \\\\ \n0044 & Barley \\\\ \n0056 & Maize (corn) \\\\ \n0071 & Rye \\\\ \n0075 & Oats \\\\ \n0079 & Millet \\\\ \n0083 & Sorghum \\\\ \n0116 & Potatoes \\\\ \n0156 & Sugar cane \\\\ \n0176 & Beans, dry \\\\ \n0236 & Soya beans \\\\ \n0946 & Buffalo \\\\ \n0960 & Cattle, dairy \\\\ \n0961 & Cattle, non-dairy \\\\ \n0976 & Sheep \\\\ \n1016 & Goats \\\\ \n1049 & Swine, market \\\\ \n1051 & Swine, breeding \\\\ \n1052 & Chickens, layers \\\\ \n1053 & Chickens, broilers \\\\ \n1068 & Ducks \\\\ \n1079 & Turkeys \\\\ \n1096 & Horses \\\\ \n1107 & Asses \\\\ \n1110 & Mules and hinnies \\\\ \n1126 & Camels \\\\ \n1177 & Llamas \\\\ \n2012 & Manufacture of fertilizers and nitrogen compounds \\\\ \n9997 & Undetermined from LULUCF \\\\ \n9998 & Undetermined from Agriculture \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n## Greenhouse Gas Emissions from Stationary and Mobile Combustion\n\nA choice was made to estimate emissions from combustion, although the global datasets that we use already have this information in the aggregate, because it was important to be able to distinguish between the different fuels driving the combustion and the sectors in which this happened. Greenhouse gas emissions from fuel combustion and fugitive emissions were estimated applying Tier 1 coefficients from the 2006 IPCC Guidelines for National Greenhouse Gas Inventories to national information on fuel uses from the United Nations Energy Database [@unsd2023] using @eq-emission-factors. We first applied conversion factors from units of volume (metric tons) to Terajoules from _Definitions, Units of Measure and Conversion Factors_ [@united_nations_energy_1987].\n\n$$\nE_{GHG,fuel} =  C_{fuel} * F_{GHG, fuel}\n$$ {#eq-emission-factors}\n\nWhere:\n\n-   $E_{GHG,fuel}=$  Emissions of a given GHG by type of fuel (kg GHG).\n-   $C_{fuel}=$ Amount of fuel combusted (TJ).\n-   $F_{GHG, fuel}=$  default emission factor of a given GHG by type of fuel (kg gas/TJ).\n\nThe UN dataset is organized according to the standard construction of Energy Balances and it features transactions related to supply, imports, stock variation, exports, transformation, industrial, and final use of all energy resources. In order to estimate emissions we focused on 39 energy resources subject to combustion or fugitive emissions (shown in @tbl-unenergy-commodities), as well as 88 energy transactions.\n\n\n::: {.cell}\n\n:::\n\n\n| Domain | Elements |\n| :- | :--------- |\n| Commodities | Animal waste, Anthracite, Aviation gasoline, Bagasse, Bio jet kerosene, Biodiesel, Biogases, Biogasoline, Black liquor, Blast furnace gas, Brown coal, Lignite brown coal, Lignite brown coal\\- recoverable resources, Brown coal briquettes, Charcoal, Coke\\-oven coke, Coke oven gas, Coking coal, Ethane, Fuel oil, Fuelwood, Gas coke, Gas oil/diesel oil, Gasoline\\-type jet fuel, Gasworks gas, Hard coal, Coal, Kerosene\\-type jet fuel, Lignite, Liquefied petroleum gas \\(lpg\\), Motor gasoline, Municipal waste, Naphtha, Natural gas \\(including lng\\), Natural gas, Other bituminous coal, Other coal products, Other hydrocarbons, Other liquid biofuels, Vegetal waste, Peat \\(for fuel use\\), Petroleum coke, Refinery gas. |\n\n: Commodities sourced from the UN Energy Database {#tbl-unenergy-commodities}\n\n# Results\n\n\n\n::: {.cell}\n\n:::\n\n\n\nThe resulting database reports GHG emissions in thousand metric tons (kt) of CO~2~eq using the  100-year Global Warming Potential (GWP) of the IPCC’s Fifth Assessment Report (AR5) for 218 countries or territories. We provide three formats for practitioners' convenience. A long format (what other efforts term \"normalized\"), where ISIC sectors are laid out in a single column, with a single column of values, a pivot format, where ISIC sectors (including an \"undetermined\" category) are arranged in columns of data values. In these two datasets, ISIC codes, ISIC descriptions, subsector codes and subsector descriptions have been concatenated into a single field for convenience. We also provide a long format version with all possible fields disaggregated, which was used to create both the long and pivot versions. These fields are:\n\n- **Area:** Country or territory name.\n- **ISO3:** Three-digit ISO country/territory name.\n- **IPCC Code:** Greenhouse gas inventory code, according to IPCC Guidelines.\n- **IPCC:** Greenhouse gas inventory description, according to IPCC Guidelnines.\n- **Category:** Description of the emissions element within the larger IPCC Code.\n- **Emission Type:** While everything is presented in kilotons of CO~2~ equivalent, this field allows the user to identify the gas responsible for the emission, which can be CO~2~, CO~2~ from biofuels, N~2~O, CH~4~, HFC, HCFC, PFC, SF~6~, NF~3~.\n- **ISIC Code:** International Industrial Classification of All Economic Activities, Revision 4, code for observations where it is possible to assign a specific activity and \"9999\" for undetermined.\n- **ISIC:** International Industrial Classification of All Economic Activities, Revision 4, description for observations where it is possible to assign a specific activity and \"Undetermined\" where not.\n- **Subsector Code:** Some observations provide economic activity information at an aggregation which is smaller than the smallest ISIC level, specifically for specific crops and animal productions (FAOSTAT). We repeat the ISIC Code for those observations outside of agriculture that don't have this description for correct ordering of the pivot dataset.\n- **Subsector:** The description of the code above.\n- **Driver:** For the energy sector (those for which the `IPCC` column starts with 3.A) it is possible to identify the specific fuel that was combusted, which generated the emission and it is presented here[^4].\n- **Unit:** A single value \"kt\" as metadata for all observations. In a previous version, we included animal and land endowments as reference and these where identified as \"An\" for number of animals and \"Ha\" for hectares. This was removed to avoid confusion for users when calculating totals.\n- **Value:** The numeric value of the observation in thousand metric tons \"kt\" (Gigagrams).\n\n[^4]: Subsector and Driver both refer to individual products, but are laid out separately in our case, because of the specific needs of PolOpT Social Accounting Matrix structures that disaggregate agriculture activities with more detail. Other databases, such as GTAP [@aguiar2019; @chepeliev2024a], combine these into a single field where they are all identified as \"drivers\" and add a second field that describes which _type_ of driver it refers to (input, output, endowment, or final consumption). Creating such a structure is trivial here by removing the agricultural drivers from the `Driver` column (for those where IPCC code starts with 3) and copying over the elements from the `Subsector` column.\n\n\n@fig-total-emissions-by-year shows Greenhouse Gas emissions for the period 1990-2022 in the resulting database. For the last year, total emissions in the database are of about 66.3 million kt CO~2~eq. This is about 13.3 million kt CO~2~eq more than the 53.0 reported by Edgar [@crippa2023]. This is because we have data on GHG emissions for some non-sovereign territories, like American Samoa (USA) or Réunion (FRA), for example, that are also reported with their respective countries total.   \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Greenhouse Gases for 220 countries and territories (Year 2022)](emissions_db_construction_files/figure-pdf/fig-total-emissions-by-year-1.pdf){#fig-total-emissions-by-year}\n:::\n:::\n\n\nWe use the case of Nigeria to exemplify differences between datasets in @tbl-nigeria-dataset-comparison. The first column shows the result of our PolOpT Emissions Dabase, the second shows the original Edgar dataset values, the third one shows a modified version of EDGAR, in which the whole section of agriculture has been replaced with FAOSTAT data (although for this comparison we removed the LULUCF part from FAO), and the last column shows the values of the World Bank World Development Indicators (only for Greenhouse Gases CO~2~, CH~4~, and N~2~O in CO~2~eq). The rows show the different emission types. Variations between datasets range from less than 1% to more than 30%. While variations remain stable with CO~2~ and N~2~O, CH~4~ is more volatile. At the same time, there is a complete discrepancy between our dataset and the Edgar based calculations of CO~2~bio, which at this  point we only can attribute to differences in elements considered for this sector, as EDGAR documentation regarding this matter appears vague in the main publication [@crippa2023]. In our case, the CO~2~ emissions of the combustion of bio jet kerosene, biodiesel, biogasoline, charcoal, biogases, bagasse, fuelwood, other liquid biofuels, animal waste, municipal waste, and vegetal waste were considered CO~2~bio, while their CH~4~ and N~2~O emissions were classified together with the emission of those gases of all other fuels. It is important to note that the confidence intervals for Tier 1 coefficients leave room for ample variation, and can vary up to +/- 30% and +/- 60%. This means that our estimates are still in the range of uncertainty when compared to other efforts.\n\n\n\n| Emission Type                     | PolOpT EMDB | EDGAR     | EDGAR + FAOSTAT | World Bank |\n| :---- | --: | --: | --: | --: |\n| Emissions (CO2)                   | 131,965.5  | 130,106.6 | 128,646.0       | 130,110.0 |\n| Emissions (CO2bio)                | 191,576.3  | 543,631.7 | 517,496.7       |           |\n| Emissions (CO2eq) from CH4 (AR5)  | 156,627.5  | 197,002.7 | 194,163.5       | 204,080.0 |\n| Emissions (CO2eq) from N2O (AR5)  | 33,692.3   | 35,333.4  | 37,630.8        | 35,330.0  |\n| Emissions (CO2eq) from HFC (AR5)  | 11,985.9   | 11,985.9  | 11,985.9        |           |\n| Emissions (CO2eq) from HCFC (AR5) | 46.5       | 46.5      | 46.5            |           |\n| Emissions (CO2eq) from PFC (AR5)  | 0.0        | 0.0       | 0.0             |           |\n| Emissions (CO2eq) from SF6 (AR5)  | 679.7      | 679.7     | 679.7           |           |\n| Total                             | 526,573.6  | 918,786.5 | 890,649.1       |           |\n| Only GHG                          | 322,285.2  | 362,442.7 | 360,440.3       | 369,520.0 |\n\n: Differences between datasets for individual emission types for Nigeria {#tbl-nigeria-dataset-comparison}\n\nAn important value added to the underlying data sources of PolOpT Emissions Database is an initial classification of emissions according to ISIC sector. This is important, because it allows practitioners of Computable General Equilibrium analysis to bridge this data with Social Accounting Matrices (which are the databases for such analyses). We made the choice to disregard the information on intermediate and final consumption of energy of industries outside the energy production and transformation sectors found in energy balances, because in the conventions of those instruments, fuels consumed by any sector for transportation purposes gets aggregated into the road sector, but that does not coincide with the corresponding ISIC classification for road transportation. Because of that, we pooled together all consumption and classified it as \"Undetermined\" for practitioners to assign it according to input shares of fuels by economic activities. @tbl-total-emissions-by-isic shows this exercise for Nigeria in 2022.\n\n\n\n::: {#tbl-total-emissions-by-isic .cell tbl-cap='Total Emissions by Sector in Nigeria (Year 2022)'}\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nSector & Total \\\\ \n\\midrule\\addlinespace[2.5pt]\n0111. Growing of cereals (except rice), leguminous crops and oil seeds & 171,667.2 \\\\ \n0112. Growing of rice & 737,928.8 \\\\ \n0113. Growing of vegetables and melons, roots and tubers & 3,849.5 \\\\ \n0114. Growing of sugar cane & 1,592.9 \\\\ \n0141. Raising of cattle and buffaloes & 3,171,358.3 \\\\ \n0142. Raising of horses and other equines & 73,597.0 \\\\ \n0143. Raising of camels and camelids & 74,186.4 \\\\ \n0144. Raising of sheep and goats & 575,298.8 \\\\ \n0145. Raising of swine/pigs & 199,882.5 \\\\ \n0146. Raising of poultry & 130,010.0 \\\\ \n0220. Logging & 14,038.8 \\\\ \n0510. Mining of hard coal & 263,922.3 \\\\ \n0610. Extraction of crude petroleum & 1,912,966.3 \\\\ \n0620. Extraction of natural gas & 523,127.9 \\\\ \n0910. Support activities for petroleum and natural gas extraction & 100,474.7 \\\\ \n1910. Manufacture of coke oven products & 3,507,043.8 \\\\ \n1920. Manufacture of refined petroleum products & 1,505,629.4 \\\\ \n2011. Manufacture of basic chemicals & 862,196.9 \\\\ \n2029. Manufacture of other chemical products n.e.c. & 1.4 \\\\ \n2310. Manufacture of glass and glass products & 11,487.5 \\\\ \n2394. Manufacture of cement, lime and plaster & 1,850,262.3 \\\\ \n2410. Manufacture of basic iron and steel & 2,152,898.7 \\\\ \n3510. Electric power generation, transmission and distribution & 23,065,891.4 \\\\ \n3520. Manufacture of gas; distribution of gaseous fuels through mains & 197,802.2 \\\\ \n3530. Steam and air conditioning supply & 115,526.4 \\\\ \n3600. Water collection, treatment and supply & 788,279.0 \\\\ \n3821. Treatment and disposal of non-hazardous waste & 1,065,713.2 \\\\ \n3822. Treatment and disposal of hazardous waste & 89,898.8 \\\\ \n5110. Passenger air transport & 345,567.2 \\\\ \n9999. Undetermined & 17,286,233.6 \\\\ \nNA. NA & 1,950,935.7 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n\n# Conclusion\n\nAs part of FAO's Policy Optimization Tool (PolOpT) [@sanchez_cicowiez_2022; @sanchez_cicowiez_2023], we sourced data from EDGAR [@crippa2023], FAOSTAT [@fao2024], and the United Nations Energy Database [@unsd2023] to provide a bridge between emissions information and social accounting matrices for Computable General Equilibrium analysis. We have created a consistent database, that allows practitioners to extend their studies to include environmental tradeoffs of economic and social policies.\n\n# References",
    "supporting": [
      "emissions_db_construction_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n\\usepackage{colortbl}\n\\usepackage{array}\n\\usepackage{anyfontsize}\n\\usepackage{multirow}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}